//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooDBEntities1 : DbContext
    {
        private static ZooDBEntities1 _context;
        public ZooDBEntities1()
            : base("name=ZooDBEntities1")
        {
        }
        public static ZooDBEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new ZooDBEntities1();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Worktable> Worktable { get; set; }
    }
}
