//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worktable
    {
        public int id { get; set; }
        public Nullable<System.DateTime> worktime { get; set; }
        public string worktimeformat { get { return Convert.ToDateTime(worktime).ToString("dd/MM/yyy HH:mm"); } }
        public int workerid { get; set; }
        public int animalid { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Person Person { get; set; }
    }
}
