//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worktable
    {
        public int id { get; set; }
        public System.DateTime worktime { get; set; }
        public int workerid { get; set; }
        public int animalid { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Person Person { get; set; }
    }
}
